/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'serviceName' : IDL.Text,
  'fileUrls' : IDL.Vec(IDL.Text),
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'serviceName' : IDL.Text,
    'fileUrls' : IDL.Vec(IDL.Text),
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };